import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAppStore } from '../lib/store';
import { FileText, Eye, Search, ShieldCheck } from 'lucide-react';

export default function ReportsPage() {
  const navigate = useNavigate();
  const { reports } = useAppStore();
  const [search, setSearch] = useState('');

  const filtered = reports.filter(r =>
    !search || [r.report_number, r.instrument.instrument_id, r.instrument.manufacturer]
      .some(f => f.toLowerCase().includes(search.toLowerCase()))
  );

  return (
    <div>
      <div className="page-header">
        <h2>Official Reports</h2>
        <p>View, inspect, and export generated OIML R-76 test certificates and compliance reports.</p>
      </div>

      <div className="filter-bar">
        <div className="filter-search" style={{ width: 280 }}>
          <Search size={14} />
          <input
            type="text"
            className="form-input"
            placeholder="Search reports by number or instrument…"
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
        </div>
      </div>

      <div className="card">
        {filtered.length === 0 ? (
          <div className="empty-state">
            <FileText />
            <h3>No reports generated</h3>
            <p>Complete instrument tests and generate reports from the instrument profile.</p>
          </div>
        ) : (
          <table className="data-table">
            <thead>
              <tr>
                <th>Report #</th>
                <th>Instrument</th>
                <th>Type</th>
                <th>Compliance</th>
                <th>Verification</th>
                <th>Generated By</th>
                <th>Rule Version</th>
                <th>Date</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              {filtered.map(r => (
                <tr key={r.id} style={{ cursor: 'pointer' }} onClick={() => navigate(`/reports/${r.id}`)}>
                  <td className="mono" style={{ fontWeight: 600 }}>{r.report_number}</td>
                  <td className="mono">{r.instrument.instrument_id}</td>
                  <td style={{ textTransform: 'capitalize' }}>{r.report_type}</td>
                  <td>
                    <span className={`status-badge ${r.compliance_result}`}>
                      {r.compliance_result.toUpperCase()}
                    </span>
                  </td>
                  <td>
                    {r.approval_status === 'approved' ? (
                      <span className="status-badge pass" style={{ display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                        <ShieldCheck size={11} /> Approved
                      </span>
                    ) : (
                      <span className="status-badge pending">Pending</span>
                    )}
                  </td>
                  <td>{r.generated_by_name}</td>
                  <td style={{ fontSize: 11, color: 'var(--steel-light)' }}>{r.rule_version}</td>
                  <td style={{ fontSize: 11, color: 'var(--steel-light)' }}>{new Date(r.generated_at).toLocaleString()}</td>
                  <td>
                    <button className="btn btn-sm btn-ghost">
                      <Eye size={12} /> Inspect
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  );
}
