import React, { useRef, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useAppStore } from '../lib/store';
import { ArrowLeft, Download, FileText, Printer, CheckCircle2, ShieldCheck } from 'lucide-react';
import jsPDF from 'jspdf';

export default function ReportDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { reports, currentUser, approveReport } = useAppStore();
  const report = reports.find(r => r.id === id);
  const reportRef = useRef<HTMLDivElement>(null);
  const [approving, setApproving] = useState(false);

  if (!report) {
    return (
      <div className="empty-state" style={{ height: '50vh' }}>
        <FileText />
        <h3>Report not found</h3>
        <button className="btn btn-secondary" style={{ marginTop: 16 }} onClick={() => navigate('/reports')}>
          <ArrowLeft size={14} /> Back to Reports
        </button>
      </div>
    );
  }

  const { instrument: inst, configuration: cfg, compliance_summary: cs } = report;
  const isApproved = report.approval_status === 'approved';
  const canApprove = (currentUser?.role === 'reviewer' || currentUser?.role === 'admin') && !isApproved;

  const handleApprove = () => {
    setApproving(true);
    approveReport(report.id, 'Metrological verification confirmed per OIML R-76 guidelines.');
    setApproving(false);
  };

  const handleDownloadPDF = () => {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const w = pdf.internal.pageSize.getWidth();
    let y = 15;
    const margin = 20;

    // Header
    pdf.setFontSize(10);
    pdf.setTextColor(100);
    pdf.text(report.organization_name, w / 2, y, { align: 'center' });
    y += 6;
    pdf.setFontSize(16);
    pdf.setTextColor(0);
    pdf.text('TEST REPORT', w / 2, y, { align: 'center' });
    y += 6;
    pdf.setFontSize(10);
    pdf.text('Non-Automatic Weighing Instrument — OIML R-76', w / 2, y, { align: 'center' });
    y += 4;
    pdf.setDrawColor(0);
    pdf.setLineWidth(0.5);
    pdf.line(margin, y, w - margin, y);
    y += 8;

    // Report Info
    pdf.setFontSize(9);
    const infoLines: [string, string][] = [
      ['Report Number:', report.report_number],
      ['Report Type:', report.report_type.toUpperCase()],
      ['Generated:', new Date(report.generated_at).toLocaleString()],
      ['Generated By:', report.generated_by_name],
      ['Rule Version:', report.rule_version],
      ['Verification Status:', isApproved ? 'APPROVED & VERIFIED' : 'PENDING REVIEW'],
    ];
    infoLines.forEach(([label, value]) => {
      pdf.setTextColor(100);
      pdf.text(label, margin, y);
      pdf.setTextColor(0);
      pdf.text(value, margin + 35, y);
      y += 5;
    });
    y += 4;

    // 1. Instrument Info
    pdf.setFontSize(11);
    pdf.setTextColor(0);
    pdf.text('1. INSTRUMENT INFORMATION', margin, y);
    y += 2;
    pdf.setLineWidth(0.2);
    pdf.line(margin, y, w - margin, y);
    y += 5;
    pdf.setFontSize(9);
    const instLines: [string, string][] = [
      ['Instrument ID:', inst.instrument_id],
      ['Manufacturer:', inst.manufacturer],
      ['Model:', inst.model],
      ['Serial Number:', inst.serial_number],
      ['Type:', inst.instrument_type],
      ['Accuracy Class:', inst.accuracy_class],
      ['Max Capacity:', `${inst.max_capacity} ${inst.unit}`],
      ['Verification Interval (e):', `${inst.verification_interval} ${inst.unit}`],
      ['Min Capacity:', `${inst.min_capacity} ${inst.unit}`],
      ['n (Max/e):', inst.num_verification_intervals.toLocaleString()],
      ['Location:', inst.location],
    ];
    instLines.forEach(([label, value]) => {
      pdf.setTextColor(100);
      pdf.text(label, margin, y);
      pdf.setTextColor(0);
      pdf.text(value, margin + 45, y);
      y += 5;
    });
    y += 6;

    // 2. Compliance Summary
    pdf.setFontSize(11);
    pdf.setTextColor(0);
    pdf.text('2. COMPLIANCE SUMMARY', margin, y);
    y += 2;
    pdf.line(margin, y, w - margin, y);
    y += 5;
    pdf.setFontSize(9);
    pdf.text(`Overall Result: ${cs.overall_result.toUpperCase()}`, margin, y);
    y += 5;
    pdf.text(`Compliance: ${cs.compliance_percentage}%`, margin, y);
    y += 5;
    pdf.text(`Total Measurements: ${cs.total_measurements} (Passed: ${cs.passed_measurements}, Failed: ${cs.failed_measurements})`, margin, y);
    y += 8;

    // 3. Test Results Table
    pdf.setFontSize(11);
    pdf.text('3. TEST RESULTS', margin, y);
    y += 2;
    pdf.line(margin, y, w - margin, y);
    y += 5;

    // Table header
    pdf.setFontSize(8);
    pdf.setTextColor(100);
    const cols = [margin, margin + 35, margin + 50, margin + 65, margin + 80, margin + 100, margin + 120];
    ['Test', 'Result', 'Meas.', 'Passed', 'Failed', 'Max Error', 'Attempts'].forEach((h, i) => {
      pdf.text(h, cols[i], y);
    });
    y += 2;
    pdf.line(margin, y, w - margin, y);
    y += 4;
    pdf.setTextColor(0);
    cs.tests.forEach(t => {
      pdf.text(t.test_name, cols[0], y);
      pdf.text(t.result.toUpperCase(), cols[1], y);
      pdf.text(String(t.measurements_count), cols[2], y);
      pdf.text(String(t.passed_count), cols[3], y);
      pdf.text(String(t.failed_count), cols[4], y);
      pdf.text(t.max_error.toFixed(4), cols[5], y);
      pdf.text(String(t.attempts_count), cols[6], y);
      y += 5;
    });
    y += 6;

    // 3.1 Detailed Measurements for each completed test
    report.test_sessions.filter(s => s.status === 'completed').forEach(session => {
      const lastAttempt = session.attempts[session.attempts.length - 1];
      if (!lastAttempt || lastAttempt.measurements.length === 0) return;

      if (y > 230) { pdf.addPage(); y = 20; }
      pdf.setFontSize(10);
      pdf.setTextColor(0);
      pdf.text(`${session.test_type.toUpperCase()} TEST — DETAILED MEASUREMENTS`, margin, y);
      y += 2;
      pdf.line(margin, y, w - margin, y);
      y += 5;

      pdf.setFontSize(8);
      pdf.setTextColor(100);
      const mCols = [margin, margin + 12, margin + 40, margin + 70, margin + 98, margin + 125];
      ['#', `Ref (${inst.unit})`, `Indicated (${inst.unit})`, 'Error', 'MPE', 'Result'].forEach((h, i) => {
        pdf.text(h, mCols[i], y);
      });
      y += 2;
      pdf.line(margin, y, w - margin, y);
      y += 4;

      pdf.setTextColor(0);
      lastAttempt.measurements.forEach(m => {
        if (y > 270) { pdf.addPage(); y = 20; }
        pdf.text(String(m.measurement_number), mCols[0], y);
        pdf.text(String(m.reference_load), mCols[1], y);
        pdf.text(String(m.indicated_value), mCols[2], y);
        pdf.text(`${m.error >= 0 ? '+' : ''}${m.error.toFixed(4)}`, mCols[3], y);
        pdf.text(`±${m.mpe.toFixed(4)}`, mCols[4], y);
        pdf.setTextColor(m.result === 'pass' ? 40 : 200, m.result === 'pass' ? 140 : 40, 40);
        pdf.text(m.result.toUpperCase(), mCols[5], y);
        pdf.setTextColor(0);
        y += 4.5;
      });
      y += 6;
    });

    // 4. Signatures
    if (y > 220) { pdf.addPage(); y = 20; }
    pdf.setFontSize(11);
    pdf.setTextColor(0);
    pdf.text('4. SIGNATURES & VERIFICATION', margin, y);
    y += 2;
    pdf.line(margin, y, w - margin, y);
    y += 10;
    pdf.setFontSize(9);
    pdf.text(`Testing Officer: ${report.generated_by_name}`, margin, y);

    if (isApproved) {
      pdf.text(`Reviewer: ${report.reviewed_by_name || 'Authorized Reviewer'} [VERIFIED]`, margin + 75, y);
      y += 5;
      pdf.setFontSize(8);
      pdf.setTextColor(30, 130, 30);
      pdf.text(`Digital Signature: ${report.signature_hash || 'SHA256-DIGITALLY-SEALED'}`, margin + 75, y);
      pdf.text(`Approval Date: ${new Date(report.reviewed_at || report.generated_at).toLocaleString()}`, margin + 75, y + 4);
      pdf.setTextColor(0);
    } else {
      pdf.text('Reviewer: ___________________________', margin + 75, y);
      y += 5;
      pdf.setFontSize(8);
      pdf.setTextColor(120);
      pdf.text('Status: Pending Official Approval', margin + 75, y);
      pdf.setTextColor(0);
    }
    y += 12;
    pdf.setFontSize(8);
    pdf.text(`Issue Date: ${new Date(report.generated_at).toLocaleDateString()}`, margin, y);

    // Footer
    pdf.setFontSize(7);
    pdf.setTextColor(150);
    pdf.text(`${report.report_number} — Generated by METROLOGY NAWI Testing Platform — ${report.rule_version}`, w / 2, 285, { align: 'center' });

    pdf.save(`${report.report_number}.pdf`);
  };

  return (
    <div>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 }}>
        <button className="btn btn-ghost" onClick={() => navigate('/reports')}>
          <ArrowLeft size={14} /> Back to Reports
        </button>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {canApprove && (
            <button className="btn btn-success" onClick={handleApprove} disabled={approving}>
              <ShieldCheck size={14} /> Sign & Approve Report
            </button>
          )}
          <button className="btn btn-secondary" onClick={() => window.print()}>
            <Printer size={14} /> Print
          </button>
          <button className="btn btn-primary" onClick={handleDownloadPDF}>
            <Download size={14} /> Generate Official PDF
          </button>
        </div>
      </div>

      {/* Report Preview */}
      <div className="report-preview" ref={reportRef}>
        <div className="report-header-section">
          <div style={{ fontSize: 11, color: '#666', marginBottom: 4 }}>{report.organization_name}</div>
          <h1>TEST REPORT</h1>
          <div style={{ fontSize: 11, color: '#666' }}>Non-Automatic Weighing Instrument — OIML R-76</div>
          {isApproved && (
            <div style={{
              display: 'inline-flex', alignItems: 'center', gap: 6, marginTop: 8,
              padding: '4px 12px', background: '#e8f5e9', border: '1px solid #81c784',
              borderRadius: 4, color: '#2e7d32', fontSize: 11, fontWeight: 600,
            }}>
              <CheckCircle2 size={14} /> VERIFIED & DIGITALLY APPROVED
            </div>
          )}
        </div>

        <div className="report-info-grid" style={{ marginBottom: 24 }}>
          <span className="report-info-label">Report Number</span><span className="report-info-value">{report.report_number}</span>
          <span className="report-info-label">Report Type</span><span className="report-info-value" style={{ textTransform: 'capitalize' }}>{report.report_type}</span>
          <span className="report-info-label">Generated</span><span className="report-info-value">{new Date(report.generated_at).toLocaleString()}</span>
          <span className="report-info-label">Generated By</span><span className="report-info-value">{report.generated_by_name}</span>
          <span className="report-info-label">Rule Version</span><span className="report-info-value">{report.rule_version}</span>
          <span className="report-info-label">Approval Status</span>
          <span className="report-info-value" style={{ color: isApproved ? '#2e7d32' : '#f57c00', fontWeight: 600 }}>
            {isApproved ? 'Approved & Signed' : 'Pending Review'}
          </span>
        </div>

        <h2>1. Instrument Information</h2>
        <div className="report-info-grid">
          <span className="report-info-label">Instrument ID</span><span className="report-info-value">{inst.instrument_id}</span>
          <span className="report-info-label">Manufacturer</span><span className="report-info-value">{inst.manufacturer}</span>
          <span className="report-info-label">Model</span><span className="report-info-value">{inst.model}</span>
          <span className="report-info-label">Serial Number</span><span className="report-info-value">{inst.serial_number}</span>
          <span className="report-info-label">Type</span><span className="report-info-value">{inst.instrument_type}</span>
          <span className="report-info-label">Accuracy Class</span><span className="report-info-value">{inst.accuracy_class}</span>
          <span className="report-info-label">Max Capacity</span><span className="report-info-value">{inst.max_capacity} {inst.unit}</span>
          <span className="report-info-label">Verification Interval (e)</span><span className="report-info-value">{inst.verification_interval} {inst.unit}</span>
          <span className="report-info-label">Min Capacity</span><span className="report-info-value">{inst.min_capacity} {inst.unit}</span>
          <span className="report-info-label">n (Max ÷ e)</span><span className="report-info-value">{inst.num_verification_intervals.toLocaleString()}</span>
          <span className="report-info-label">Location</span><span className="report-info-value">{inst.location}</span>
          <span className="report-info-label">Owner</span><span className="report-info-value">{inst.owner_organization}</span>
        </div>

        <h2>2. Compliance Summary</h2>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12, padding: '8px 12px', background: cs.overall_result === 'pass' ? '#e8f5e9' : '#fce4e4', borderRadius: 4 }}>
          <strong style={{ fontSize: 14, color: cs.overall_result === 'pass' ? '#2e7d32' : '#c62828' }}>
            {cs.overall_result === 'pass' ? '✓ COMPLIANT' : '✕ NON-COMPLIANT'}
          </strong>
          <span style={{ fontSize: 11, color: '#555' }}>
            Compliance: {cs.compliance_percentage}% — {cs.passed_measurements}/{cs.total_measurements} measurements within MPE
          </span>
        </div>

        <h2>3. Test Results</h2>
        <table>
          <thead>
            <tr>
              <th>Test</th><th>Result</th><th>Measurements</th><th>Passed</th><th>Failed</th><th>Max Error</th><th>Attempts</th>
            </tr>
          </thead>
          <tbody>
            {cs.tests.map((t, i) => (
              <tr key={i}>
                <td>{t.test_name}</td>
                <td style={{ fontWeight: 600, color: t.result === 'pass' ? '#2e7d32' : '#c62828' }}>
                  {t.result.toUpperCase()}
                </td>
                <td>{t.measurements_count}</td>
                <td>{t.passed_count}</td>
                <td>{t.failed_count}</td>
                <td>{t.max_error.toFixed(4)}</td>
                <td>{t.attempts_count}</td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Detailed measurements for each test */}
        {report.test_sessions.filter(s => s.status === 'completed').map(session => {
          const lastAttempt = session.attempts[session.attempts.length - 1];
          if (!lastAttempt || lastAttempt.measurements.length === 0) return null;
          return (
            <React.Fragment key={session.id}>
              <h3 style={{ textTransform: 'capitalize' }}>{session.test_type} Test — Measurements</h3>
              <table>
                <thead>
                  <tr>
                    <th>#</th><th>Reference ({inst.unit})</th><th>Indicated ({inst.unit})</th>
                    {session.test_type === 'eccentricity' && <th>Position</th>}
                    <th>Error</th><th>MPE</th><th>Result</th>
                  </tr>
                </thead>
                <tbody>
                  {lastAttempt.measurements.map(m => (
                    <tr key={m.id}>
                      <td>{m.measurement_number}</td>
                      <td>{m.reference_load}</td>
                      <td>{m.indicated_value}</td>
                      {session.test_type === 'eccentricity' && <td style={{ textTransform: 'capitalize' }}>{m.position?.replace('-', ' ')}</td>}
                      <td style={{ color: m.result === 'pass' ? '#2e7d32' : '#c62828' }}>
                        {m.error >= 0 ? '+' : ''}{m.error.toFixed(4)}
                      </td>
                      <td>±{m.mpe.toFixed(4)}</td>
                      <td style={{ fontWeight: 600, color: m.result === 'pass' ? '#2e7d32' : '#c62828' }}>{m.result.toUpperCase()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </React.Fragment>
          );
        })}

        <h2>4. Signatures & Digital Seal</h2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 48, marginTop: 24 }}>
          <div>
            <div style={{ borderBottom: '1px solid #999', marginBottom: 4, height: 40, display: 'flex', alignItems: 'flex-end', paddingBottom: 4 }}>
              <span style={{ fontSize: 13, fontFamily: 'monospace', color: '#333' }}>{report.generated_by_name}</span>
            </div>
            <div style={{ fontSize: 11, color: '#666' }}>Testing Officer / Operator</div>
          </div>
          <div>
            <div style={{ borderBottom: '1px solid #999', marginBottom: 4, height: 40, display: 'flex', alignItems: 'flex-end', paddingBottom: 4 }}>
              {isApproved ? (
                <div style={{ color: '#2e7d32', fontSize: 12, fontWeight: 600, display: 'flex', alignItems: 'center', gap: 4 }}>
                  <ShieldCheck size={16} /> {report.reviewed_by_name} (Digitally Signed)
                </div>
              ) : (
                <span style={{ fontSize: 11, color: '#999', fontStyle: 'italic' }}>Pending Review & Signature</span>
              )}
            </div>
            <div style={{ fontSize: 11, color: '#666' }}>Reviewer / Approver</div>
            {isApproved && (
              <div style={{ fontSize: 9, color: '#666', fontFamily: 'monospace', marginTop: 4 }}>
                Hash: {report.signature_hash} · {new Date(report.reviewed_at!).toLocaleString()}
              </div>
            )}
          </div>
        </div>

        <div style={{ marginTop: 32, borderTop: '1px solid #ccc', paddingTop: 8, fontSize: 9, color: '#999', textAlign: 'center' }}>
          {report.report_number} — Generated by METROLOGY NAWI Testing Platform — {report.rule_version}
        </div>
      </div>
    </div>
  );
}
